### ISSUE TITLE
Need to add karma-sinon as a plugin

### ISSUE THREAD

**Issue by harmoney-markc** [yanoosh/karma-sinon#7]
Hi,

I had trouble setting up karma-sinon. I was getting: Error: No provider for "framework:sinon"! (Resolving: framework:sinon).

I resolved it by adding 'karma-sinon' to the plugin section of my karma config.

Is this always required? If so would you please add it to your readme?

Cheers,
Mark

**Comment by sloria** [comment]
> By default, Karma loads all sibling NPM modules which have a name starting with karma-*. You can also explicitly list plugins you want to load via the plugins configuration setting. 

https://karma-runner.github.io/0.12/config/plugins.html

So if you add a `plugins` entry to your config, you will need to explicitly specify every plugin you want to use.
