### ISSUE TITLE
Stop working after sinons update to 1.15.0

### ISSUE THREAD

**Issue by icaaq** [yanoosh/karma-sinon#8]
I get this now that sinon has updated to `1.15.0`
```
...\node_modules\sinon\lib/../pkg/sinon.js" does not match any file
```
If i have `sinon 1.14.1` installed separately  it works just fine

**Comment by apturtia** [comment]
Hi,
Sinon 1.15.0 seems broken. The release does not contain the pkg directory that contains the different processed sinons.js files.
Related sinon issue: https://github.com/cjohansen/Sinon.JS/issues/761

**Comment by elachys** [comment]
see  https://github.com/yanoosh/karma-sinon/blob/master/package.json#L31 
Please do not use * as a version number.

**Comment by kentcdodds** [comment]
Just ran into this issue as well [Travis Build](https://travis-ci.org/formly-js/angular-formly/builds/66258395)

**Comment by kentcdodds** [comment]
Actually, I think that the real fix is for this issue https://github.com/cjohansen/Sinon.JS/issues/761 (mentioned by @apturtia) to get fixed. Though I'd still recommend getting rid of the `*` :-)

**Comment by ljharb** [comment]
Nothing should EVER depend on `*` or `latest` - @yanoosh are you still maintaining this package?

**Comment by yanoosh** [comment]
Yes I still maintaining this package. When I change to fixed version then I should bump version in my package on every update of sinon. Current configuration is good enough for most user so I prefer to not touch this `*`.

**Comment by ljharb** [comment]
@yanoosh ok but your package is broken as of sinon 1.15, so you already have to do that. Can you at least fix it so it works?

**Comment by ljharb** [comment]
More to the point, you *should* have to bump the version in your package on every update of sinon, since you should be testing your package with every update of sinon.

**Comment by yanoosh** [comment]
As far as I know everything works fine. Where is written that I should bump version?

**Comment by ljharb** [comment]
@yanoosh is this a fix you're planning to make, or should we fork the project so a working version exists?

**Comment by ljharb** [comment]
@yanoosh there's been no commits in a year, despite your claim that you're still maintaining the package :-/ is this a fix you can make? If not, would you be willing to add me as a collaborator/publisher so I can take care of it? If not, would you let us know, so I can fork it and publish a working version? (I'd prefer to avoid forking if at all possible)
